version: "3.8"
services:
  api:
    container_name: api
    build: 
      context: .
      dockerfile: Dockerfile-srv
    restart: always
    env_file:
     - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    # volumes:
    #   -  .:/usr/src/app
    working_dir: /usr/src/api
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

 